{# {%- for dc in cookiecutter.inventory.dc_list %}
---
  - name: Build Switch configuration
    hosts: {{ dc.dc_name }}
    connection: local
    gather_facts: false
    collections:
      - arista.avd
      - arista.cvp
    tasks:
      # - name: 'reset local folders for output'
      #   tags: [build, generate]
      #   import_role:
      #     name: arista.avd.build_output_folders
{%- raw %}
      - name: 'create cvp structure config folder: {{documentation_dir_name}}'
        tags: [build, generate]
        file:
          path: '{{playbook_dir}}/intended/structured_configs/cvp/'
          state: directory
          mode: 0755
        delegate_to: localhost
{%- endraw %}
      - name: generate intended variables
        tags: [build, generate]
        import_role:
          name: arista.avd.eos_l3ls_evpn
      - name: generate device intended config and documentation
        tags: [build, generate]
        import_role:
          name: eos_cli_config_gen
      # - name: 'Generate documentation with mkdocs'
      #   tags: [build, generate]
      #   import_role:
      #     name: publish-documentation
      #   run_once: True
  
  - name: Configuration deployment with CVP
    hosts: cv_server
    connection: local
    gather_facts: false
    collections:
      - arista.avd
      - arista.cvp
    tasks:
      - name: run CVP provisioning
        import_role:
          name: arista.avd.eos_config_deploy_cvp
        vars:
          container_root: '{{ cookiecutter.cvp.container_root }}'
          configlets_prefix: '{{ cookiecutter.cvp.configlets_prefix }}'
          device_filter: '{{ cookiecutter.cvp.device_filter }}'
          state: present
{%- endfor %} #}