---
  - name: Reset CVP configuration
    hosts: cv_server
    connection: local
    gather_facts: false
    collections:
      - arista.avd
      - arista.cvp
    tasks:
      - name: run CVP provisioning
        import_role:
          name: arista.avd.eos_config_deploy_cvp
        vars:
          container_root: '{{cookiecutter.cvp.container_root}}'
          configlets_prefix: '{{cookiecutter.cvp.configlets_prefix}}'
          # device_filter: 'DC1-'
          state: absent